[development]
address = "localhost"
port = 8000
workers = 2
log = "normal"
secret_key = "Fd0Tto05dQ0KXV3H+7cizerjMQnSzeaxc/H5S/cOpmU="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 4000
workers = 2
log = "normal"
secret_key = "Fd0Tto05dQ0KXV3H+7cizerjMQnSzeaxc/H5S/cOpmU="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 3010
workers = 2
log = "critical"
secret_key = "Fd0Tto05dQ0KXV3H+7cizerjMQnSzeaxc/H5S/cOpmU="
limits = { forms = 32768 }

